// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/list-processes.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.105.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-processes.ts
var list_processes_default = defineTool({
  name: "list_processes",
  title: "Listar procesos de compra",
  description: "Lista los procesos de compra visibles para el usuario, con filtros opcionales por criticidad, etapa, tipo o texto de b\xFAsqueda.",
  inputSchema: {
    search: z.string().trim().min(1).optional().describe("Texto a buscar en el nombre o n\xFAmero del proceso."),
    criticality: z.enum(["alta", "media", "baja"]).optional().describe("Filtrar por criticidad."),
    stage: z.string().trim().min(1).optional().describe("Filtrar por etapa actual (current_stage)."),
    process_type: z.string().trim().min(1).optional().describe("Filtrar por tipo de proceso (PC, CT, LT, PM)."),
    limit: z.number().int().min(1).max(100).default(20).describe("M\xE1ximo de procesos a devolver.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, criticality, stage, process_type, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("purchase_processes").select(
      "id, pdc_number, name, project, process_type, current_stage, criticality, estimated_amount, currency, required_on_site_date, responsible_name, updated_at"
    ).order("updated_at", { ascending: false }).limit(limit ?? 20);
    if (criticality) query = query.eq("criticality", criticality);
    if (stage) query = query.eq("current_stage", stage);
    if (process_type) query = query.eq("process_type", process_type);
    const safeSearch = search?.replace(/[.,()]/g, "");
    if (safeSearch) query = query.or(`name.ilike.%${safeSearch}%,pdc_number.ilike.%${safeSearch}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { processes: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-process.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var get_process_default = defineTool2({
  name: "get_process",
  title: "Detalle de un proceso",
  description: "Devuelve el detalle de un proceso de compra (por id o por n\xFAmero de proceso) junto con sus etapas y comentarios recientes.",
  inputSchema: {
    id: z2.string().uuid().optional().describe("Identificador \xFAnico del proceso."),
    pdc_number: z2.string().trim().min(1).optional().describe("N\xFAmero del proceso, por ejemplo PC-0001.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id, pdc_number }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    if (!id && !pdc_number) {
      return { content: [{ type: "text", text: "Indica id o pdc_number" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("purchase_processes").select("*").limit(1);
    query = id ? query.eq("id", id) : query.eq("pdc_number", pdc_number);
    const { data: process, error } = await query.maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!process) return { content: [{ type: "text", text: "Proceso no encontrado" }], isError: true };
    const [{ data: stages }, { data: comments }] = await Promise.all([
      supabase.from("process_stages").select("id, name, status, sort_order").eq("process_id", process.id).order("sort_order", { ascending: true }),
      supabase.from("process_comments").select("id, body, created_at, author_user_id").eq("process_id", process.id).order("created_at", { ascending: false }).limit(10)
    ]);
    const payload = { process, stages: stages ?? [], comments: comments ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-alerts.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";
var list_alerts_default = defineTool3({
  name: "list_alerts",
  title: "Listar alertas",
  description: "Lista las alertas de seguimiento visibles para el usuario, opcionalmente filtradas por severidad o estado.",
  inputSchema: {
    severity: z3.string().trim().min(1).optional().describe("Filtrar por severidad de la alerta."),
    status: z3.string().trim().min(1).optional().describe("Filtrar por estado de la alerta."),
    limit: z3.number().int().min(1).max(100).default(25).describe("M\xE1ximo de alertas a devolver.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ severity, status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("alerts").select("*").order("created_at", { ascending: false }).limit(limit ?? 25);
    if (severity) query = query.eq("severity", severity);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { alerts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-projects.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^3.25.76";
var list_projects_default = defineTool4({
  name: "list_projects",
  title: "Listar proyectos",
  description: "Lista los proyectos visibles para el usuario junto con su informaci\xF3n b\xE1sica.",
  inputSchema: {
    search: z4.string().trim().min(1).optional().describe("Texto a buscar en el nombre del proyecto."),
    limit: z4.number().int().min(1).max(100).default(25).describe("M\xE1ximo de proyectos a devolver.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("projects").select("*").order("created_at", { ascending: false }).limit(limit ?? 25);
    const safeSearch = search?.replace(/[.,()]/g, "");
    if (safeSearch) query = query.ilike("name", `%${safeSearch}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { projects: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/add-process-comment.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z5 } from "npm:zod@^3.25.76";
var add_process_comment_default = defineTool5({
  name: "add_process_comment",
  title: "Comentar un proceso",
  description: "Agrega un comentario al hilo de seguimiento de un proceso de compra, como el usuario autenticado.",
  inputSchema: {
    process_id: z5.string().uuid().describe("Identificador del proceso a comentar."),
    body: z5.string().trim().min(1).max(4e3).describe("Texto del comentario.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ process_id, body }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data: process, error: processError } = await supabase.from("purchase_processes").select("id, tenant_id").eq("id", process_id).maybeSingle();
    if (processError) return { content: [{ type: "text", text: processError.message }], isError: true };
    if (!process) return { content: [{ type: "text", text: "Proceso no encontrado o sin acceso" }], isError: true };
    const { data, error } = await supabase.from("process_comments").insert({
      process_id: process.id,
      tenant_id: process.tenant_id,
      author_user_id: ctx.getUserId(),
      body
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Comentario agregado al proceso ${process.id}.` }],
      structuredContent: { comment: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "wlpfhcqlubokwnszjycg";
var mcp_default = defineMcp({
  name: "procurement-by-inhr",
  title: "Procurement by InHR",
  version: "0.1.0",
  instructions: "Herramientas de Procurement by InHR (Pro.Curem Flow) para procesos de compra industriales. Usa `list_processes` y `get_process` para consultar procesos, hitos y comentarios; `list_alerts` para alertas de seguimiento; `list_projects` para proyectos; y `add_process_comment` para dejar un comentario en un proceso. Todo se ejecuta como el usuario autenticado y respeta sus permisos.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_processes_default, get_process_default, list_alerts_default, list_projects_default, add_process_comment_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
